const data = {
    "chimney": "Called the chimney, the vertical tube of the Bunsen burner directs methane gas upwards into a jet, providing fuel for the fire. Do not touch it while the flame is burning because it is hot, and don’t put anything above it that is flammable or will be negatively affected by fire.",
    "gas-tube": "The gas tube of a Bunsen Burner carries pressurised gas, normally methane, to the burner. This tube is normally attached to the gas valve, which releases a steady, controlled flow of gaseous gas into the burner. The tube is connected to the burner at the bottom, and ensures that the gas and oxygen from the oxygen valve are evenly mixed before it is burned. In addition, this tube is often made of rubber, which helps prevent gas leakages.",
    "nozzle": "The nozzle of the burner is where the flame and remaining uncombusted gas emerge. This component is often made with metal, which is resistant to burning. Bunsen burners have a nozzle that is often quite wide, which helps maintain a controlled gas pressure.",
    "oxygen-valve": "The oxygen valve of a Bunsen burner allows for oxygen to enter the burner and contribute to the oxidation of the gas. This valve contains a screw mechanism, which allows for controlled oxygen release into the burner. The oxygen valve is one of two ways to control the flame’s size, the other way being the gas valve. In addition, the oxygen valve is one of the key components for creating a successful flame, as it controls the amount of oxygen that enters the burner, thereby influencing the size of the flame.",
    "flint": "The flint is a tool that has a piece of flint attached to a small cup with a textured piece of steel in it. When the flint is struck against the steel, sparks are created.",
    "step1": "First, open the gas valve slightly to release some fuel into the burner. It’s not advised to keep the valve open for too long at a time without a flame, as an excessive build-up of flammable gases is not conducive to human life. Once you have some gas flowing into the burner, you can strike the flint over the flame. If three strike attempts have passed without a flame, let the gas dissipate before trying again.",
    "step2": "Begin by pressing the flint portion hard against the steel plate. Then, squeeze the handle of the flint so that it rubs against the steel plate and generates sparks. It’s recommended that you have the sparks facing away from you during this process, by facing the small cup away from you.",
    "step3": "There are two ways one can adjust the size of the flame on a Bunsen burner: changing the flow of gas and changing how open the oxygen valve is. The Bunsen burner’s flame is a combustion reaction between oxygen and methane, kick-started with the heat of a flint striker. Increasing the amount of methane and oxygen increases the size of the flame, done by rotating the gas valve in the right direction or opening the oxygen valve, respectively. The reason is because more reactant is introduced into the reaction, increasing the rate of reaction. Decreasing either reactant slows the reaction, and makes the flame smaller."
};

const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]').forEach((item) => {
    item.title = data[item.id]
    new bootstrap.Tooltip(item)
})